import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#FAF9F5',
  },
  keyboardView: {
    flex: 1,
  },
  navHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 24,
    paddingVertical: 12,
  },
  backIcon: {
    padding: 10,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: 99,
  },
  navTitle: {
    fontFamily: 'Figtree-ExtraBold',
    fontWeight: '800',
    fontSize: 18,
    color: '#1F2937',
  },
  spacer: {
    width: 40,
    height: 40,
  },
  scrollContent: {
    paddingHorizontal: 24,
    paddingBottom: 24,
  },
  stateToggle: {
    flexDirection: 'row',
    padding: 4,
    backgroundColor: '#FAF9F5',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: 12,
    marginBottom: 20,
  },
  toggleOption: {
    flex: 1,
    paddingVertical: 10,
    alignItems: 'center',
    borderRadius: 10,
    backgroundColor: '#FFFFFF',
  },
  toggleText: {
    fontFamily: 'Figtree-SemiBold',
    fontWeight: '600',
    fontSize: 14,
    color: '#4B5563',
  },
  photoUpload: {
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    height: 130,
    backgroundColor: '#FAF9F5',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderStyle: 'dashed',
    borderRadius: 12,
    marginBottom: 20,
  },
  photoUploadTitle: {
    fontFamily: 'Figtree-Bold',
    fontWeight: '700',
    fontSize: 13,
    color: '#1F2937',
  },
  photoUploadSub: {
    fontFamily: 'Figtree-Regular',
    fontWeight: '400',
    fontSize: 11,
    color: '#9CA3AF',
  },
  fieldGroup: {
    gap: 6,
    marginBottom: 20,
  },
  fieldLabel: {
    fontFamily: 'Figtree-Bold',
    fontWeight: '700',
    fontSize: 13,
    color: '#1F2937',
    marginBottom: 6,
  },
  fieldInput: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: 14,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  fieldInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  fieldInputText: {
    fontFamily: 'Figtree-Regular',
    fontWeight: '400',
    fontSize: 14,
    color: '#1F2937',
  },
  submitArea: {
    paddingHorizontal: 24,
    paddingVertical: 24,
  },
  submitButton: {
    paddingVertical: 16,
    borderRadius: 16,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    height: 'auto',
  },
  submitText: {
    fontFamily: 'Figtree-Bold',
    fontWeight: '700',
    fontSize: 16,
    color: '#FFFFFF',
  },
  // Responsive Web Styles
  webContainer: {
    maxWidth: 1040,
    width: '100%',
    alignSelf: 'center',
    paddingHorizontal: 32,
    paddingTop: 36,
    paddingBottom: 48,
  },
  webHeader: {
    marginBottom: 28,
  },
  webTitle: {
    fontFamily: 'Figtree-ExtraBold',
    fontWeight: '800',
    fontSize: 32,
    color: '#1F2937',
    marginBottom: 6,
  },
  webSubtitle: {
    fontFamily: 'Figtree-Regular',
    fontSize: 15,
    color: '#6B7280',
  },
  webRow: {
    flexDirection: 'row',
    gap: 32,
    alignItems: 'flex-start',
  },
  webLeftCol: {
    width: 360,
    gap: 16,
  },
  webRightCol: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    padding: 32,
  },
  tipsCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    padding: 20,
    gap: 8,
  },
  tipsTitle: {
    fontFamily: 'Figtree-Bold',
    fontWeight: '700',
    fontSize: 14,
    color: '#1F2937',
    marginBottom: 4,
  },
  tipsText: {
    fontFamily: 'Figtree-Regular',
    fontSize: 13,
    color: '#6B7280',
    lineHeight: 18,
  },
});
