import { StyleSheet } from 'react-native';
import { Colors } from '../../constants/Colors';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: Colors.background,
  },
  header: {
    paddingHorizontal: 24,
    paddingTop: 16,
    paddingBottom: 24,
  },
  locationContainer: {
    gap: 4,
  },
  locationLabel: {
    fontFamily: 'Figtree-Medium',
    fontSize: 12,
    color: Colors.textMuted,
  },
  locationSelector: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  locationText: {
    fontFamily: 'Figtree-Bold',
    fontSize: 15,
    color: Colors.textDark,
  },
  greetingContainer: {
    paddingHorizontal: 24,
    marginBottom: 24,
  },
  greetingTitle: {
    fontFamily: 'Figtree-ExtraBold',
    fontSize: 24,
    color: Colors.textDark,
    marginBottom: 4,
  },
  greetingSubtitle: {
    fontFamily: 'Figtree-Medium',
    fontSize: 15,
    color: Colors.textMuted,
  },
  categoriesContainer: {
    marginBottom: 32,
  },
  categoriesList: {
    paddingHorizontal: 24,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 24,
    marginBottom: 16,
  },
  sectionTitle: {
    fontFamily: 'Figtree-Bold',
    fontSize: 18,
    color: Colors.textDark,
  },
  seeAllText: {
    fontFamily: 'Figtree-Bold',
    fontSize: 14,
    color: Colors.primary,
  },
  listContainer: {
    paddingHorizontal: 24,
    paddingBottom: 24,
  },
  gridItemContainer: {
    flex: 1,
    marginHorizontal: 8,
    marginBottom: 24,
    maxWidth: '31%',
  },
  webScrollContainer: {
    flexGrow: 1,
    alignItems: 'center',
    backgroundColor: '#FAF9F5',
  },
  webContainer: {
    width: '100%',
    maxWidth: 1440,
    paddingHorizontal: 40,
    paddingTop: 32,
    paddingBottom: 64,
  },
  webHeroCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    padding: 32,
    marginBottom: 32,
  },
  webHeroTitle: {
    fontFamily: 'Figtree-Bold',
    fontSize: 28,
    color: '#111827',
    marginBottom: 8,
  },
  webHeroSubtitle: {
    fontFamily: 'Figtree-Regular',
    fontSize: 14,
    color: '#4B5563',
    marginBottom: 24,
  },
  webSearchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    paddingHorizontal: 16,
    paddingVertical: 14,
    gap: 12,
  },
  webSearchInput: {
    flex: 1,
    fontFamily: 'Figtree-Regular',
    fontSize: 14,
    color: '#111827',
    outlineStyle: 'none' as any,
  },
  webContentRow: {
    flexDirection: 'row',
    gap: 32,
    alignItems: 'flex-start',
    width: '100%',
  },
  webSidebar: {
    width: 260,
    gap: 20,
  },
  webSidebarCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    padding: 20,
  },
  webSidebarTitle: {
    fontFamily: 'Figtree-Bold',
    fontSize: 16,
    color: '#111827',
    marginBottom: 16,
  },
  webOccurrenceBtn: {
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 10,
    marginBottom: 6,
  },
  webOccurrenceBtnActive: {
    backgroundColor: '#3366FF',
  },
  webOccurrenceText: {
    fontFamily: 'Figtree-Medium',
    fontSize: 14,
    color: '#374151',
  },
  webOccurrenceTextActive: {
    fontFamily: 'Figtree-SemiBold',
    color: '#FFFFFF',
  },
  webCategoryItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 8,
    position: 'relative',
  },
  webCategoryIndicator: {
    position: 'absolute',
    left: 0,
    width: 3,
    height: 18,
    backgroundColor: '#3366FF',
    borderRadius: 2,
  },
  webCategoryText: {
    fontFamily: 'Figtree-Regular',
    fontSize: 14,
    color: '#4B5563',
    marginLeft: 14,
  },
  webCategoryTextActive: {
    fontFamily: 'Figtree-Bold',
    color: '#111827',
  },
  webMainContent: {
    flex: 1,
  },
  webSectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  webSectionTitle: {
    fontFamily: 'Figtree-Bold',
    fontSize: 20,
    color: '#111827',
  },
  webSectionSubtitle: {
    fontFamily: 'Figtree-Regular',
    fontSize: 13,
    color: '#6B7280',
    marginTop: 4,
  },
  webSortContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  webSortLabel: {
    fontFamily: 'Figtree-Regular',
    fontSize: 13,
    color: '#6B7280',
  },
  webSortButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: 8,
    backgroundColor: '#FFFFFF',
  },
  webSortText: {
    fontFamily: 'Figtree-SemiBold',
    fontSize: 13,
    color: '#111827',
  },
  webGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 24,
    width: '100%',
  },
  webCard: {
    width: 'calc(50% - 12px)' as any,
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    overflow: 'hidden',
  },
  webCardImage: {
    width: '100%',
    height: 220,
    backgroundColor: '#F3F4F6',
  },
  webCardBody: {
    padding: 18,
  },
  webCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  webCardCategory: {
    fontFamily: 'Figtree-SemiBold',
    fontSize: 11,
    color: '#9CA3AF',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  webCardTitle: {
    fontFamily: 'Figtree-Bold',
    fontSize: 17,
    color: '#111827',
    marginBottom: 12,
  },
  webCardInfoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 4,
  },
  webCardInfoText: {
    fontFamily: 'Figtree-Regular',
    fontSize: 13,
    color: '#6B7280',
  },
});
